### ISSUE TITLE
support for metadata, Mac extended attributes, etc.

### ISSUE THREAD

**Issue by fracai** [gilbertchen/duplicacy#143]
I was originally just concerned with MacOS resource forks, but was reminded of the [Backup Bouncer](https://github.com/n8gray/Backup-Bouncer) test suite.

Macs currently split non-data fork data to AppleDouble encoded "**._filename**" files when saving to non-Mac systems.

These forks can be listed and displayed with the _xattr_ command.

The easiest way to create a file with a resource fork is dragging a URL or text selection to the desktop to create a "**webloc**" or "**textClipping**" file.

**Comment by gilbertchen** [comment]
Resource forks are backed up as extended attributes.  However, when they are restored on an OS without resource fork support, "._filname" files will not be created.

**Comment by fracai** [comment]
Yeah, I was looking through the code earlier and realized you were indeed looking at extended attributes. When listing a backup I saw a resource fork file listed with zero size and assumed attributes were being skipped. I'll going to give a try at running Backup Bouncer.

**Comment by fracai** [comment]
I created [scripts](https://github.com/fracai/Backup-Bouncer/tree/master/scripts) for testing rsync and Duplicacy against BackupBouncer. Please let me know if I have duplicacy configured incorrectly as in my tests I couldn't get resource forks to be restored. BackupBouncer reports a number of failures, but I'm primarily interested in resource forks.

[bbouncer-duplicacy.txt](https://github.com/gilbertchen/duplicacy/files/1265700/bbouncer-duplicacy.txt)

**Comment by gilbertchen** [comment]
This is a bug.  The attributes are discarded if there are no patterns provided to the restore command.  But if there are (which means you're restore one file or a subset of files), attributes are restored correctly.

This bug has been fixed by https://github.com/gilbertchen/duplicacy/commit/dfa61132794762cad5574a686f6691fa67136d81

**Comment by sharpjs** [comment]
I'd really like to see the post-fix Backup Bouncer results.  That would save me the time of doing them myself. 😄   Duplicacy is on my short list for a CrashPlan replacement, but it's a non-starter if the results are anything like that posted above.

**Comment by fracai** [comment]
I checked out the latest source, but I haven't had a chance to build or test yet. Hopefully soon. I'll certainly post here once I have. I'm in the same shot. Duplicacy is the current leader.

**Comment by fracai** [comment]
Looks like resource forks are now restored. There are still some BackupBouncer failures, but for the most part they're dates or file flags. There seems to be some issue with resource forks on hard linked files, but I haven't dug in to see what that is (ah, I bet it's that the hardlinks aren't restored to matching inodes). I'd love to see a perfect score, but for most people it's likely hitting the important notes.

I'd say this issue can either be re-purposed for general BackupBouncer compliance, closed and a new issue opened, or just closed if BackupBouncer isn't a priority.

Thanks for fixing the restore issue.

[bbouncer-duplicacy-fix.txt](https://github.com/gilbertchen/duplicacy/files/1273611/bbouncer-duplicacy-fix.txt)

**Comment by nikjft** [comment]
It looks like it's still failing to recover permissions. Is this expected behavior?

**Comment by fracai** [comment]
I assumed they weren't being stored to begin with

**Comment by gilbertchen** [comment]
Permissions are stored and are supposed to restored.  The failure on basic-permissions was a surprise to me too.

**Comment by fracai** [comment]
It looks like the "basic permissions" issue is that the restore isn't setting the Sticky or SetUID bits.

```
/Volumes/Src/00-basic-permissions:
total 0
0 drwxr-xr-x  9 arno staff 306 Sep  5 22:15 ./
0 drwxr-xr-x 22 arno staff 816 Sep  5 22:15 ../
0 -rwxrwxrwt  1 arno staff   0 Sep  5 22:15 owned-by-me*
0 -rw-r-Sr--  1 arno staff   0 Sep  5 22:15 owned-by-me-guid
0 -rw-r--r--  1 arno staff   0 Sep  5 22:15 owned-by-me-sticky
0 -rwSr--r--  1 arno staff   0 Sep  5 22:15 owned-by-me-suid
0 -rw-r--r--  1 root wheel   0 Sep  5 22:15 owned-by-root
0 -rw-r--r--  1 _www _www    0 Sep  5 22:15 owned-by-www
0 drwxrwxrwt  2 arno staff  68 Sep  5 22:15 some-dir/

/Volumes/Dst/00-basic-permissions:
total 0
0 drwxr-xr-x  9 arno staff 306 Sep  5 22:15 ./
0 drwxr-xr-x 22 arno staff 816 Sep  5 22:16 ../
0 -rwxrwxrwx  1 arno staff   0 Sep  5 22:15 owned-by-me*
0 -rw-r--r--  1 arno staff   0 Sep  5 22:15 owned-by-me-guid
0 -rw-r--r--  1 arno staff   0 Sep  5 22:15 owned-by-me-sticky
0 -rw-r--r--  1 arno staff   0 Sep  5 22:15 owned-by-me-suid
0 -rw-r--r--  1 root wheel   0 Sep  5 22:15 owned-by-root
0 -rw-r--r--  1 _www _www    0 Sep  5 22:15 owned-by-www
0 drwxrwxrwx  2 arno staff  68 Sep  5 22:15 some-dir/
```

**Comment by nriley** [comment]
I tried testing Duplicacy 2.1.0 with Backup Bouncer and got a different error message — how did you test?  The keychain errors are expected (root doesn't have a keychain) but I have no idea what to do with the "EOF" one. I'm OK with duplicacy not backing up FIFOs and devices — it’s clearly not designed to back up a whole disk — but wanted to see how it was doing on the permissions.

```
% pwd                         
/Volumes/Src
% sudo cat .duplicacy         
/Users/nicholas/src/Backup-Bouncer/duplicacy
% sudo duplicacy backup -stats
Storage set to sftp://backup@banjo.ad.sabi.net/BanjoDestination/Duplicacy/BackupBouncer
2018-03-10 15:56:46.568 duplicacy[76512:24452544] Keychain Get: Error Code: -25300
Enter SSH password:******************************
No previous backup found
Indexing /Volumes/Src
Skipped non-regular file 90-fifo/some-fifo
Skipped non-regular file 95-devices/devvn0
Skipped non-regular file 95-devices/devzero
Incomplete snapshot loaded from /Users/nicholas/src/Backup-Bouncer/duplicacy/incomplete
Listing all chunks
Skipped 61 files from previous incomplete backup
Failed to upload the file snapshots/bbsrc/1: EOF
Incomplete snapshot saved to /Users/nicholas/src/Backup-Bouncer/duplicacy/incomplete
```

**Comment by amarcu5** [comment]
New pull request #417 passes Backup-Bouncer's critical basic permissions test, let's hope @gilbertchen approves!

**Comment by ricka** [comment]
#417 was merged, does this fix/close this issue?

**Comment by gilbertchen** [comment]
I believe this has been fixed.

**Comment by photocyte** [comment]
Hi there,

Out of curiosity, I reran Backup Bouncer with duplicacy and rsync on MacOS, using the most up to date versions of software as of 2020.  Results submitted below for your interest:

MacOS | 10.15.6
-- | --
Backup Bouncer | https://github.com/n8gray/Backup-Bouncer ; Sep 11 2011.
rsync | MacPorts, 3.2.3
duplicacy | 2.6.2 (670CBC)
/Volumes/Src | GUID / HFS+
/ | GUID / APFS


```
##rsync copied to local filesystem:
rsync -aHX /Volumes/Src/ /Users/tim/Desktop/duplicacy_cli_restore_test
./bbouncer verify -d /Volumes/Src /Users/tim/Desktop/duplicacy_cli_restore_test
---
Verifying:    basic-permissions ... FAIL (Critical)
Verifying:           timestamps ... ok (Critical)
Verifying:             symlinks ... ok (Critical)
Verifying:    symlink-ownership ... FAIL 
Verifying:            hardlinks ... ok (Important)
Verifying:       resource-forks ... 
   Sub-test:             on files ... ok (Critical)
   Sub-test:  on hardlinked files ... ok (Important)
Verifying:         finder-flags ... ok (Critical)
Verifying:         finder-locks ... FAIL 
Verifying:        creation-date ... FAIL 
Verifying:            bsd-flags ... FAIL 
Verifying:       extended-attrs ... 
   Sub-test:             on files ... ok (Important)
   Sub-test:       on directories ... ok (Important)
   Sub-test:          on symlinks ... ok 
Verifying: access-control-lists ... 
   Sub-test:             on files ... FAIL (Important)
   Sub-test:              on dirs ... FAIL (Important)
Verifying:                 fifo ... ok 
Verifying:              devices ... FAIL 
Verifying:          combo-tests ... 
   Sub-test:  xattrs + rsrc forks ... ok 
   Sub-test:     lots of metadata ... FAIL
```

```
./duplicacy restore -r 1 -storage gcd://backup_bouncer -ignore-owner -overwrite
./bbouncer verify -d /Volumes/Src /Users/tim/Desktop/duplicacy_cli_restore_test 
---
Verifying:    basic-permissions ... FAIL (Critical)
Verifying:           timestamps ... ok (Critical)
Verifying:             symlinks ... ok (Critical)
Verifying:    symlink-ownership ... FAIL 
Verifying:            hardlinks ... FAIL (Important)
Verifying:       resource-forks ... 
   Sub-test:             on files ... ok (Critical)
   Sub-test:  on hardlinked files ... FAIL (Important)
Verifying:         finder-flags ... ok (Critical)
Verifying:         finder-locks ... FAIL 
Verifying:        creation-date ... FAIL 
Verifying:            bsd-flags ... FAIL 
Verifying:       extended-attrs ... 
   Sub-test:             on files ... ok (Important)
   Sub-test:       on directories ... ok (Important)
   Sub-test:          on symlinks ... FAIL 
Verifying: access-control-lists ... 
   Sub-test:             on files ... FAIL (Important)
   Sub-test:              on dirs ... FAIL (Important)
Verifying:                 fifo ... FAIL 
Verifying:              devices ... FAIL 
Verifying:          combo-tests ... 
   Sub-test:  xattrs + rsrc forks ... ok 
   Sub-test:     lots of metadata ... FAIL 
```

The basic permissions failure aren't too surprising, as that test has files with owners like www and root, so duplicacy would need to be root to recreate that.

The major failures to date seem to be: hardlinks, resource forks on hardlinks, and, the lack of xattr on symlinks.  It would be nice if duplicacy could match what rsync can do given non-root permissions (things like fifo and devices seem tangential).  

Another Mac thought: Seeing as duplicacy doesn't recreate hardlinks (rather, it makes independent copies of files), duplicacy backups of Time Machine backups probably wouldn't work.
